
runtime: nodejs
env: flex

#automatic_scaling:
  #max_num_instances: 1

#resources:
  #cpu: 1
  #memory_gb: 0.5
  #disk_size_gb: 10

env_variables:
  HOST_TYPE: gae

  NT_PORT: 8080
  NT_LANG: en
  NT_REPORT_DIR:
  # default or static (subdomains: see www/vhost.json)
  NT_START_PAGE: default

  NT_API_KEY: APISECRETKEY
  NT_TOKEN_ISS: nervatura
  NT_TOKEN_KEY: TOKENSECRETKEY
  NT_TOKEN_EXP: 1h
  NT_CERT_GOOGLE: https://www.googleapis.com/robot/v1/metadata/x509/securetoken@system.gserviceaccount.com
  NT_HASHTABLE:
  NT_POOL_MIN: 0
  NT_POOL_MAX: 10
  NT_CONTENT_LENGTH: 20000

# EMAIL SMTP SETTINGS:
  #NT_SMTP_HOST: YOUR_SMTP_HOST
  #NT_SMTP_PORT: YOUR_SMTP_PORT
  #NT_SMTP_SECURE: true
  #NT_SMTP_USER: YOUR_SMTP_USER
  #NT_SMTP_PASSWORD: YOUR_SMTP_PASSWORD

# MAILJET SETTINGS:
  #NT_MJ_APIKEY_PUBLIC: YOUR_MJ_APIKEY_PUBLIC
  #NT_MJ_APIKEY_PRIVATE: YOUR_MJ_APIKEY_PRIVATE

# SQL databases
# e.g. postgres://sqluser:password@/cloudsql/my-awesome-project:us-central1:my-cloud-sql-instance
  #NT_ALIAS_PGDEMO: postgres://YOUR_SQL_USER:YOUR_SQL_PASSWORD@/cloudsql/YOUR_INSTANCE_CONNECTION_NAME/YOUR_SQL_DATABASE
  #NT_ALIAS_MYDEMO: mysql://YOUR_SQL_USER:YOUR_SQL_PASSWORD@/cloudsql/YOUR_INSTANCE_CONNECTION_NAME/YOUR_SQL_DATABASE

#beta_settings:
  #cloud_sql_instances: YOUR_INSTANCE_CONNECTION_NAME

skip_files:
- ^(.*/)?app\.yaml
- ^Dockerfile
- ^\.dockerignore
- ^\.gitignore
- ^\.git/.*
- ^\.openshift/.*
- ^\.vscode/.*
- ^node_modules/(.*/)?
- ^data/storage/(.*/)?
